title: "HSE-CoSec-Materials"
description: "Archive for notes"
baseurl: ""
url: "https://HSE-CoSec-Materials.github.io"

remote_theme: "mmistakes/minimal-mistakes"

header_pages:
  - README.md

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

github:
  repository_url: "https://github.com/HSE-CoSec-Materials/HSE-CoSec-Materials.github.io"

markdown: kramdown
highlighter: rouge
