title: "HSE-CoSec-Materials
description: "Archive for notes"
baseurl: "" # Укажите, если сайт размещён не в корне репозитория
url: "https://HSE-CoSec-Materials.github.io

remote_theme: "mmistakes/minimal-mistakes"

header_pages:
  - README.md

collections:
  reports:
    output: true
    permalink: /reports/:path/

defaults:
  - scope:
      path: ""
      type: "reports"
    values:
      layout: "single"
      author_profile: false

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-feed

github:
  repository_url: "https://github.com/HSE-CoSec-Materials/HSE-CoSec-Materials.github.io"

markdown: kramdown
highlighter: rouge

# Вывод PDF в виде списка
include: ["Material-Vault"]
